language: cpp

compiler: gcc

before_install:
   - set
   - uname -a
   - cat /etc/issue
   - find .
   - sudo apt-get update -qq
   - sudo apt-get install -qq cmake sqlite3 qt4-dev-tools

before_script:
   - mkdir build
   - cd build
   - cmake ..

script: make

notifications:
   email:
      - kaplan2539@gmail.com
   on_success: change
   on_failure: always
